SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `docker_basics` DEFAULT CHARACTER SET latin1 ;
USE `docker_basics` ;

DROP TABLE IF EXISTS `docker_basics`.`todos` ;

CREATE TABLE IF NOT EXISTS `docker_basics`.`todos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `todos` JSON NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
